simonmoore23/clowning-around-entertainment-job-board

- index.html
This can be added to as we build application out, but essential parts are there.
> Updated a basic version of a html page for job board. 

- assets/js/script.js
Allows function of filtering jobs - can be later adapted and changed for the employer to filter templates for jobs they want to submit.
> initial basic javascript function added for filtering jobs

- index.html
added basic button for reference for jscript coding to create functionality
> button for login page created

- assets/js/script.js
> modal logic with opening and closing functions added

- config/connection.js
- db/schema.sql
connection code to pull sequelize info from .env file for name, password and user.
> Connection code for config folder

- .env.EXAMPLE
- config/connection.js
- models/index.js
- models/post.js
- models/user.js
- package.json
- seeds/index.js
- seeds/postSeed.js
- seeds/userSeed.js
I've added the seeds for users and some sample post. I've tested it and it populated with no errors after I fixed some bugs in the model files.
> added seeds. fixed bugs in models

- .env.EXAMPLE
and input their own mySQL details as necessary
const routes = require('./controllers'); line commented out for now as controllers folder not currently created and therefore causing server.js file to throw error
> Example file created for enviromental variables so users can amend

- package-lock.json
> added .env

- index.html
Link added to header for CDN .
> bootstrap link added to html

- controllers/index.js
Create new router object, fetch specific routes for home page and attach them to route path of central router.
> shell code for controllers/index.js

- controllers/api/index.js
- controllers/api/user-routes.js
coded for the user-routes and the api index.js.
still need to match it up with the expression-session to keep track of the cookies
> created code for user-routes & api index.js

- controllers/api/postRoutes.js
- controllers/api/userRoutes.js
- models/Post.js
- models/index.js
- models/user.js
- package.json
- seeds/postSeed.json
- seeds/userSeed.json
- server.js
Changed to camelcase for consistency and to avoid transcription errors . this way they will match const names in JS.
> changed keys in models to camelcase.changed references to these keys.

- public/css/style.css
gave the 'header-container' a background colour with opacity to clean up the look and make buttons/title more visible.
only added:
background-color: rgba(6, 34, 6, 0.608);
> Update to header section.

- controllers/api/userRoutes.js
THERE IS A BUG IN THIS CODE - FIX COMING RIGHT AFTER
On user creation, postcode provided by user is sent to the postcodes.io API, and from extracted data this user is updated with region/town
> grab data from postcode and update user location

- public/js/editUser.js
create edit users folder with relevant user information
> created edituser.js folder & contents

- public/css/style.css
- public/js/script.js
- views/layouts/main.handlebars
Created in html and public front-end javascript
> Feature - new job post modal

- controllers/api/userRoutes.js
I have added put request in userRoutes so that they work with the editUsers form
> added put request in userRoutes

- views/apply.handlebars
> apply.handlebars

- public/css/style.css
- public/js/script.js
- views/profile.handlebars
Added extra div and h3 to give titles to each section. Centralised text of titles.
> Change of layout on main profile page

- controllers/api/postRoutes.js
- controllers/applyRoutes.js
- public/js/deletePost.js
- views/layouts/main.handlebars
- views/profile.handlebars
created deletePosts.js & added delete into the applyRoutes. Also amended button into profile.handlebars
> created delete functions

- public/js/newPost.js
- public/js/script.js
- views/layouts/main.handlebars
Imbedded external public/js/newPost.js file in main.handlebars to allow execution of code. Form handler for new job posting wasn't grabbing numeral value for salary from the job post form modal. Now correctly rendering. Formatting on salary in script.js removed to allow for handling by numeral library included as new technology demonstration within project
> New job posts now rendering on profile and main page.

- public/css/style.css
- views/apply.handlebars
- views/profile.handlebars
edited styling in profile page for job listing section to ensure delete button is on the right hand side
> Delete Button Styling

- public/css/style.css
on home page to black for the titles. This pulls from #post-title element, and therefore had to be changed from white to black to match existing text styles.
> Text color changed 
